# --- docker-compose.local.minio.n8n.yml ---
version: "3.9"

services:
  ncat:
    build: .
    env_file:
      - .env.local.minio.n8n
    ports:
      - "8080:8080"
    volumes:
      - storage:/app/storage
      - logs:/app/logs
    restart: unless-stopped
    depends_on:
      - minio
      - minio-init
    networks:
      - nca-network

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    volumes:
      - minio_data:/data          # ← named volume terug
    restart: unless-stopped
    networks:
      - nca-network

  minio-init:
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      mc alias set myminio http://minio:9000 minioadmin minioadmin123;
      mc mb myminio/nca-toolkit-local --ignore-existing;
      mc anonymous set public myminio/nca-toolkit-local;
      echo 'MinIO bucket nca-toolkit-local created and configured as public';
      "
    networks:
      - nca-network

  n8n:
    build:
      context: .
      dockerfile: Dockerfile.n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://localhost:5678/
      - GENERIC_TIMEZONE=UTC
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - nca-network

volumes:
  storage:
  logs:
  n8n_data:
  minio_data:                      # ← volume declaratie

networks:
  nca-network:
    driver: bridge
